version: '3.9'

services:
  db:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  api:
    image: node:18.16.1
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    command: ['tail', '-f', '/dev/null']

volumes:
  db:
    driver: local